[versions]

kotlinx-serialization = "1.10.0"
kotlinx-coroutines = "1.10.2"

apacheMaven-core = "3.9.12"
apacheMaven-pluginTools = "3.15.2"

slf4j = "2.0.17"

ktor = "3.4.0"

dokka = "2.1.0"

reposilite = "3.5.26"

gradlePlugin-nmcp = "1.4.3"
gradlePlugin-devPublish = "0.4.2"

[libraries]

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

apacheMaven-pluginApi = { module = "org.apache.maven:maven-plugin-api", version.ref = "apacheMaven-core" }
apacheMaven-core = { module = "org.apache.maven:maven-core", version.ref = "apacheMaven-core" }
apacheMaven-pluginAnnotations = { module = "org.apache.maven.plugin-tools:maven-plugin-annotations", version.ref = "apacheMaven-pluginTools" }

apacheMaven-model = { module = "org.apache.maven:maven-model", version.ref = "apacheMaven-core" }
apacheMaven-modelBuilder = { module = "org.apache.maven:maven-model-builder", version.ref = "apacheMaven-core" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }


ktorClient-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktorClient-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktorClient-resources = { module = "io.ktor:ktor-client-resources", version.ref = "ktor" }
ktorClient-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktorClient-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktorClient-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }

ktorSerialization-kotlinxJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

reposilite = { module = "com.reposilite:reposilite", version.ref = "reposilite" }

gradlePlugin-devPublish = { module = "dev.adamko.gradle:dev-publish-plugin", version.ref = "gradlePlugin-devPublish" }
gradlePlugin-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
gradlePlugin-nmcp = { module = "com.gradleup.nmcp:nmcp", version.ref = "gradlePlugin-nmcp" }

[plugins]
